[package]
name = "awesome-rewrite-it-in-rust"
version = "0.1.0"
authors = ["Takayuki Maeda <41065217+TaKO8Ki@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
